# Generated by Django 4.2.3 on 2023-07-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
